source 'http://ruby.taobao.org/'


gem 'rake'
gem 'bson_ext'
gem 'mechanize'
gem 'sanitize'
 
gem 'httparty'
 
#gem 'mongoid_spacial'

gem 'mongoid_geospatial'
gem 'mongoid' , "~> 3.0.0"
gem 'bson_ext'
