source 'http://ruby.taobao.org/'


# NOTE:
# * if failed in installing 'bson_ext', try 'gem install bundler --pre' first as mentioned in https://jira.mongodb.org/browse/RUBY-551
# * if failed in installing 'unf_ext', try 'sudo ln -s /usr/bin/gcc /usr/bin/gcc-4.2' (tried out in mac 10.8.2 with xcode command line tool installed)
gem 'rake'
gem 'mongoid' , "~> 3.0.0"
gem 'bson_ext'
gem 'mechanize'
gem 'sanitize'

gem 'feedzirra'
gem 'httparty'

gem 'mongoid_spacial'
